language: haskell

matrix:
  allow_failures:
    - env: GHCVER=head  CABALVER=1.22
    - env: GHCVER=7.4.2 CABALVER=1.18

env:
 - GHCVER=head   CABALVER=1.22
 - GHCVER=7.10.1 CABALVER=1.22
 - GHCVER=7.8.3  CABALVER=1.18
 - GHCVER=7.6.3  CABALVER=1.18
 - GHCVER=7.4.2  CABALVER=1.18

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - travis_retry cabal-$CABALVER install --only-dependencies --force-reinstalls

